### ISSUE TITLE
Q: What is stanza?

### ISSUE THREAD

**Issue by sirinath** [ucb-bar/firrtl#151]
What is stanza? Can you direct me to a website or documentation?

**Comment by CuppoJava** [comment]
Hi Suminda. 

Stanza is a new general purpose programming language being designed in our lab. It's designed specifically to be good at architecting complex programs, and to be productive across the whole software development timeline, from prototyping through production. We chose to design and develop the original FIRRTL implementation in Stanza because it offered us the most productive framework out of all the existing languages, and it has served us well.

You can visit lbstanza.org for more information. That's a very old website, and we are preparing a public release within this month.

  -Patrick

**Comment by sirinath** [comment]
Thanks. Is the language open sourced?

**Comment by CuppoJava** [comment]
Yes. It has a 3-clause BSD license.

**Comment by sirinath** [comment]
Where is the repo?

**Comment by CuppoJava** [comment]
The repo is not public yet. We are preparing a public release this month.
But all the source files are available in the download package on the
website.

Cheers.
  -Patrick

**Comment by sirinath** [comment]
Can you ping me when the repo becomes available?

**Comment by CuppoJava** [comment]
Sure!
