### ISSUE TITLE
NameSpace "tryName" 

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/firrtl#453]
I wanted to try to see if I'd have any name space collisions for a bunch of pad modules, so I tried using "tryName". However, the Seq of pad names I used had some duplicate names... which caused tryName to fail (b/c tryName adds to the namespace). I don't think "tryName" should be adding the name to the nameSpace if it returns Boolean. That's what newName should be for...

**Comment by jackkoenig** [comment]
The idea of `tryName` is "I want this exact name, tell me if I can't have it so that I can make a decision based on failure." `newName` is different in that it's just saying "I want a name based on this prefix, just give me a legal one."

The function you are describing is `contains` which doesn't exist because it hasn't been needed yet. Feel free to add it if you want it.
